"""Article 50 transparency: machine-readable marking and disclosure.

Art. 50(2) requires providers of generative systems to mark output as
artificially generated "in a machine-readable format". Two mechanisms ship here,
and the distinction between them is the whole point:

- **A zero-width marker embedded in the text.** Survives copy-paste and plain
  transport. Does NOT survive re-generation, translation, or a determined
  stripper — and the docstring says so rather than letting a compliance report
  imply a robustness the mechanism does not have.
- **A detached metadata block** (C2PA-shaped). Survives nothing on its own, but
  is what an asset pipeline actually carries and what a downstream verifier reads.

Neither is a watermark in the adversarial-robustness sense. Marking output is a
transparency duty; resisting a motivated remover is a research problem, and a
tool that conflates them sells false assurance.
"""
from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

#: Zero-width characters carrying one bit each. Invisible in every renderer,
#: preserved by plain-text copy, stripped by any normaliser that filters Cf
#: category codepoints — which is the honest limit of the technique.
_ZERO, _ONE, _SENTINEL = "​", "‌", "⁠"
_MARKER_RE = re.compile(f"{_SENTINEL}[{_ZERO}{_ONE}]{{16,}}{_SENTINEL}")

DEFAULT_DISCLOSURE_EN = "This content was generated by an AI system."
DEFAULT_DISCLOSURE_TR = "Bu içerik bir yapay zekâ sistemi tarafından üretilmiştir."


def _encode_bits(payload: str) -> str:
    bits = "".join(f"{b:08b}" for b in payload.encode("utf-8"))
    return _SENTINEL + "".join(_ONE if b == "1" else _ZERO for b in bits) + _SENTINEL


def _decode_bits(marker: str) -> str | None:
    body = marker.strip(_SENTINEL)
    bits = "".join("1" if ch == _ONE else "0" for ch in body)
    if len(bits) % 8:
        return None
    try:
        return bytes(int(bits[i:i + 8], 2) for i in range(0, len(bits), 8)).decode("utf-8")
    except (ValueError, UnicodeDecodeError):
        return None


@dataclass
class Watermark:
    system: str
    model: str = "unspecified"
    issued_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    content_hash: str = ""

    def tag(self) -> str:
        """The short payload embedded in the text. Kept small — every byte is 8
        invisible characters, and a kilobyte of them is no longer invisible."""
        return f"AAI|{self.system[:24]}|{self.issued_at[:10]}"

    def to_dict(self) -> dict[str, Any]:
        return {"system": self.system, "model": self.model,
                "issued_at": self.issued_at, "content_hash": self.content_hash}


def watermark(
    text: str,
    *,
    system: str,
    model: str = "unspecified",
    visible_disclosure: bool | str = False,
    locale: str = "en",
) -> tuple[str, Watermark]:
    """Mark `text` as AI-generated. Returns the marked text and the record.

    `visible_disclosure` is separate from the embedded marker because Art. 50 asks
    for different things in different places: (2) wants machine-readable marking,
    (1) and (4) want a person to be *informed*. An invisible marker satisfies the
    first and none of the second.
    """
    wm = Watermark(system=system, model=model,
                   content_hash=hashlib.sha256((text or "").encode("utf-8")).hexdigest()[:16])
    out = (text or "") + _encode_bits(wm.tag())
    if visible_disclosure:
        line = visible_disclosure if isinstance(visible_disclosure, str) else (
            DEFAULT_DISCLOSURE_TR if locale == "tr" else DEFAULT_DISCLOSURE_EN
        )
        out = f"{out}\n\n{line}"
    return out, wm


def verify_watermark(text: str) -> dict[str, Any]:
    """Report whether a marker is present and what it says.

    `present: False` means no marker was found — never that the content is
    human-made. Absence of a mark is not evidence of absence of generation, and
    a verifier that implies otherwise is worse than none.
    """
    m = _MARKER_RE.search(text or "")
    if not m:
        return {"present": False, "tag": None,
                "note": "No marker found. This does not establish that the content is "
                        "human-authored — only that this marker is absent."}
    tag = _decode_bits(m.group(0))
    return {"present": True, "tag": tag, "valid": bool(tag and tag.startswith("AAI|")),
            "note": "A marker is present. It attests to marking, not to provenance: "
                    "markers can be copied onto other content."}


def strip_watermark(text: str) -> str:
    """Remove any marker. Provided so a customer can test their own removal risk."""
    return _MARKER_RE.sub("", text or "")


def metadata_block(
    *,
    system: str,
    model: str,
    content_type: str = "text",
    prompt_hash: str | None = None,
    locale: str = "en",
) -> dict[str, Any]:
    """Detached, C2PA-shaped assertion for a generated asset.

    `prompt_hash`, not the prompt: the provenance record must be publishable, and
    a prompt routinely contains the customer data the whole Kit exists to keep in.
    """
    return {
        "@context": "https://c2pa.org/statements/v1",
        "claim_generator": "AtherosAI Compliance Kit",
        "assertions": [
            {"label": "c2pa.ai_generated", "data": {
                "generated_by": model, "system": system, "content_type": content_type}},
            {"label": "eu.ai_act.transparency", "data": {
                "article": "Art. 50(2)",
                "disclosure": DEFAULT_DISCLOSURE_TR if locale == "tr" else DEFAULT_DISCLOSURE_EN,
                "machine_readable": True}},
        ],
        "prompt_hash": prompt_hash,
        "issued_at": datetime.now(timezone.utc).isoformat(),
    }


def disclosure_text(locale: str = "en") -> str:
    return DEFAULT_DISCLOSURE_TR if locale == "tr" else DEFAULT_DISCLOSURE_EN


def as_json(block: dict[str, Any]) -> str:
    return json.dumps(block, indent=2, ensure_ascii=False)
